### ISSUE TITLE
左下のGithubアイコンのリンク先が静岡県対策サイトのリポジトリになっている

### ISSUE THREAD

**Issue by aktnk** [hiroyuki-ichikawa/fujicity_covid19#17]
## 起こっている問題 / The Problem
- 左下のGithubアイコンのリンク先が静岡県対策サイトのリポジトリになっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13390370/105804151-695ecc00-5fe2-11eb-9831-68bf0fcc1185.png)

## 期待する見せ方・挙動 / Expected Behavior
- リンク先は、https://github.com/hiroyuki-ichikawa/fujicity_covid19 とすること

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザでhttps://stopcovid19-fuji.netlify.app/ にアクセス
2. 左側メニューの下部にあるGithubアイコンをクリックする
3. 静岡県 新型コロナウイルス感染症対策サイト のリポジトリが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hiroyuki-ichikawa** [comment]
富士市版のGitHubにリンク先を変更

**Comment by aktnk** [comment]
下記にて修正されたことを確認
https://github.com/hiroyuki-ichikawa/fujicity_covid19/commit/760d7f204bd225039dc592be56d9824381eea9ec
