### ISSUE TITLE
左下のFacebookアイコンのリンク先が静岡県防災になっている

### ISSUE THREAD

**Issue by aktnk** [hiroyuki-ichikawa/fujicity_covid19#18]
## 起こっている問題 / The Problem
- 左下のFacebookアイコンのリンク先が静岡県防災になっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13390370/105804593-86e06580-5fe3-11eb-9840-c3d304d00763.png)

## 期待する見せ方・挙動 / Expected Behavior
- 富士市のFacebook https://www.facebook.com/FujiCity へのリンクすること

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザでhttps://stopcovid19-fuji.netlify.app/ にアクセス
2. 左側メニューの下部にあるFacebookアイコンをクリックする
3. 静岡県 防災のFacebookが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hiroyuki-ichikawa** [comment]
富士市の公式FBページにリンク先を変更

**Comment by aktnk** [comment]
下記にて修正されたことを確認
https://github.com/hiroyuki-ichikawa/fujicity_covid19/commit/760d7f204bd225039dc592be56d9824381eea9ec
