### ISSUE TITLE
左下のTwitterアイコンのリンク先が静岡県防災になっている

### ISSUE THREAD

**Issue by aktnk** [hiroyuki-ichikawa/fujicity_covid19#19]
## 起こっている問題 / The Problem
- 左下のTwitterアイコンのリンク先が静岡県防災になっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13390370/105804942-4d5c2a00-5fe4-11eb-9016-df13a96ccbfc.png)

## 期待する見せ方・挙動 / Expected Behavior
- 富士市のtwitter https://twitter.com/Fujishi_jp へのリンクになっていること 

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザでhttps://stopcovid19-fuji.netlify.app/ にアクセス
2. 左側メニューの下部にあるTwitterアイコンをクリックする
3. 静岡県 防災のTwitterが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hiroyuki-ichikawa** [comment]
富士市の公式Twitterにリンク先を変更

**Comment by aktnk** [comment]
下記にて修正されたことを確認
https://github.com/hiroyuki-ichikawa/fujicity_covid19/commit/760d7f204bd225039dc592be56d9824381eea9ec
