### ISSUE TITLE
Androidスマホのレスポンシブ対応を改善する

### ISSUE THREAD

**Issue by aktnk** [hiroyuki-ichikawa/fujicity_covid19#20]
## 改善詳細 / Details of Improvement
- 「富士市の市章と富士市の文字からなるイメージ」のサイズを小さくする

## スクリーンショット / Screenshot

<img src="https://user-images.githubusercontent.com/13390370/105805692-eb042900-5fe5-11eb-9bc8-333c3fc59376.png" width="350px">

## 期待する見せ方・挙動 / Expected behavior
- iPhoneのように表示されること
<img src="https://user-images.githubusercontent.com/13390370/105806339-2521fa80-5fe7-11eb-97f8-59138596d860.PNG" width="350px">

## 動作環境・ブラウザ / Environment
-  Android
- Chrome /  Firefox / Edge⇒いずれも同じ表示となった

**Comment by hrsano645** [comment]
#29 closedなのでこちらもclosedにします👍
