### ISSUE TITLE
陽性患者の性別の「公表望まず」の多言語対応

### ISSUE THREAD

**Issue by jandknagaya** [hiroyuki-ichikawa/fujicity_covid19#21]
## 起こっている問題 / The Problem
- 陽性患者の性別の「公表望まず」が多言語対応できていない

## スクリーンショット / Screenshot

![属性性別の「公表望まず」](https://user-images.githubusercontent.com/65159906/106004457-96040800-60f6-11eb-8174-40cfe6b6682f.PNG)

## 期待する見せ方・挙動 / Expected Behavior
1. 多言語に対応すること

## 起こっている問題の再現手段 / Steps to Reproduce
1. 多言語対応選択メニューで日本語以外を選択する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
下記にて修正されたことを確認
https://github.com/hiroyuki-ichikawa/fujicity_covid19/commit/b39a837e7a0e3b1262113676c3a4dd92cc562c9e
