### ISSUE TITLE
サイトのロゴサイズが大きい

### ISSUE THREAD

**Issue by hrsano645** [hiroyuki-ichikawa/fujicity_covid19#27]
## 起こっている問題 / The Problem
- 対策サイトのロゴサイズが大きい
- モバイル版でレイアウトがやや崩れてしまう

## スクリーンショット / Screenshot

PC版

![image](https://user-images.githubusercontent.com/23502/106349459-4a797600-6311-11eb-86bd-a6f2f1ffac56.png)

モバイル版

![image](https://user-images.githubusercontent.com/23502/106349505-a512d200-6311-11eb-9331-766cf5c7eda8.png)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19-fuji.netlify.app へアクセス
2. chrome dev tools でロゴのelementでチェック
3. モバイル版もchrome dev toolsのモバイル向けのレイアウト表示モードで確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
chrome dev toolsで見た内容では、

- 富士市版のlogo.svgのサイズは 300 * 89 pxでした。
- 参考に、静岡県側のアイコンは 111 * 28 px のサイズのようです。

**Comment by aktnk** [comment]
モバイル版に関する指摘は　#20 と同じですね。

**Comment by hrsano645** [comment]
> モバイル版に関する指摘は　#20 と同じですね。

ですね。重複していたのでこちらcloseしておきます。
