### ISSUE TITLE
陽性患者数のグラフに2021年の月が表示されない

### ISSUE THREAD

**Issue by aktnk** [hiroyuki-ichikawa/fujicity_covid19#32]
## 起こっている問題 / The Problem
- 陽性患者数のグラフの横軸に2021年の月が表示されない

## スクリーンショット / Screenshot

![Screenshot_2021-02-02-22-54-26-12.png](https://user-images.githubusercontent.com/13390370/106610628-56cc3000-65aa-11eb-90db-7499b4793b45.png)

## 期待する見せ方・挙動 / Expected Behavior
- 静岡県のサイトと同様に年月が表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザで対策サイトにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
関連のPRがmergeされていたので終了します。お疲れ様です👍
