### ISSUE TITLE
GithubActionsのreviewがエラーになる

### ISSUE THREAD

**Issue by euledge** [hiroyuki-ichikawa/fujicity_covid19#35]
## 改善詳細 / Details of Improvement
- GithubActionsのワークフローreviewdogがエラーでESlintが実行されない。

ワークフローのモジュールでも同様の報告が上がっています。
https://github.com/reviewdog/action-eslint/issues/61

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1209580/107138590-a159fd80-6958-11eb-8325-2003841e3911.png)

## 期待する見せ方・挙動 / Expected behavior
- ESLintが実行されてreviedogがエラーにならないこと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
こちらのissue PRとりこみましたので終了します。ありがとうございます！
